spring.application.name=Mzalendo POS
spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3307/mzalendo_schema}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
